### ISSUE TITLE
Doc Template - Component

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#134]
Design component template, within default template #132 .

**Comment by jamesmelzer** [comment]
![doc component](https://user-images.githubusercontent.com/1207666/42818923-19a73316-89a0-11e8-9646-dddee1716b65.png)

## Peer review

@patrickmckowen - Mind taking a look?

**Comment by patrickmckowen** [comment]
@jamesmelzer A few thoughts:

* Whitespace is a key aspect of Spirit.  I wonder if we air out the component blocks a bit more. Perhaps 12x top and bottom?  See how that feels.
* I'm not sure about the elevation change on hover; I wonder if it will be distracting if you are trying to copy a longer bit of code, like markup for vertical nav.
* With providing that sense of spaciousness in mind, I wonder if the code container is a bit tight.  Perhaps a 3x inset padding?

Still not sure about how the branding / structure of the page / color will work, but feel like I'll be closer to providing better direction next week once the local nav explorations start to firm up.

**Comment by jamesmelzer** [comment]
@patrickmckowen in your first bullet, do you mean inside the component, or above/below it? 

Switched to 3x all the way around; with 3x above the middle divider, too. The exception is the copy link below the divider, which I positioned more tightly since it lacks a bounding box - 1.5x above/below. 

How about we see how it is with the hover elevation in code, and if we hate it we pull it out? 

![doc component](https://user-images.githubusercontent.com/1207666/43095506-114f242e-8e84-11e8-84e7-020601b96fd3.png)

**Comment by patrickmckowen** [comment]
@ismaeltoure7 thoughts?

**Comment by kevinmpowell** [comment]
@jamesmelzer 
* The side by side button example code pair is a bit of a cheat. There are few components that have states that can be displayed in this manner. I think it's fine to use it where we can, but I don't think it's a strong representative example of the component template in general. More often when we have multiple states, we'll want to stack them vertically. Think Form Elements (Input, Textarea), or Button Groups and Pagination.
* Because most components will need to stack, we'll need a labelling mechanism that works well for those examples. We've found that labelling the upper right corner of the list of examples typically works best:
![screen shot 2018-07-25 at 1 44 25 pm](https://user-images.githubusercontent.com/979463/43220900-dd68e6fc-9010-11e8-85f0-b8060bde76f8.png)
* Also due to the height of example stacks, I'm not convinced the "shadow on hover" will be a meaningful effect. If the code/example pair is sufficiently tall, or if the bottom of the pair is scrolled off the page, the overall effect will be lost. I encourage a true border, however faint, around the example area, and no effect on hover with the exception of an animated underline on the "Copy To Clipboard" link.
Additional doc components I'd like to see design for:
* Do/Don't
* Reference table for CSS modifier classes

**Comment by ismaeltoure7** [comment]
@jamesmelzer This looks really good! I agree with @patrickmckowen about considering a subtle, persistent, elevation on code block.

**Comment by kevinmpowell** [comment]
> I agree with @patrickmckowen about considering a subtle, persistent, elevation on code block.

👍 I agree with that as well in lieu of a faint border around the example area per my feedback.

**Comment by jamesmelzer** [comment]
@kevinmpowell @patrickmckowen 

Vertical alignment 
![screen shot 2018-07-25 at 4 30 51 pm](https://user-images.githubusercontent.com/1207666/43225848-2d05b2f0-9028-11e8-8ee2-162193326aaa.png)

Persistent outer shadow, via elevation 1
![screen shot 2018-07-25 at 4 31 05 pm](https://user-images.githubusercontent.com/1207666/43225856-32f092ac-9028-11e8-93c2-68afed9c7203.png)

**Comment by kevinmpowell** [comment]
Looks good, and to clarify, in cases (like button) where we can get away with a horizontal alignment and it looks good, I'm all for it.

**Comment by jamesmelzer** [comment]
Agreed. I've found this useful for all sorts of inputs, where showing small multiples of states is handy.
