### ISSUE TITLE
Do/Don't Doc Component

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#16]
### Deliver

* Skin the component to match the visual style of the overall design system

### Process

Build #16

**Comment by jamesmelzer** [comment]
For review

![screen shot 2018-07-27 at 1 41 01 pm](https://user-images.githubusercontent.com/1207666/43337932-1144a702-91a3-11e8-8a54-70d48c0f254a.png)

**Comment by patrickmckowen** [comment]
@jamesmelzer This is great.

And actually the “don’t use giant icons” and “don’t use uncommon icons without a label” were the only things I could think of yesterday in terms of guidelines.

**Comment by jamesmelzer** [comment]
Adding an example of an editorial do/don't (no illustration) 

![screen shot 2018-07-30 at 3 40 22 pm](https://user-images.githubusercontent.com/1207666/43419447-ea36fbce-940e-11e8-8696-b96378ebfd08.png)

**Comment by jamesmelzer** [comment]
Looking for peer review. Remove your assignment when done. 

- [ ] @patrickmckowen 
- [ ] @kevinmpowell

**Comment by kevinmpowell** [comment]
I actually miss the side-by-side comparison of the image variation when I see the text variation. It's harder for me to think in terms of "Instead of this...do this."

I like the design, but I think sticking closer to the image version will convey more effective comparison. See this morningstar example:

![screen shot 2018-07-30 at 3 32 15 pm](https://user-images.githubusercontent.com/979463/43421931-c2904e82-940d-11e8-8a68-d3e121603d93.png)

**Comment by jamesmelzer** [comment]
@kevinmpowell Yeah, I hear you. The text-only is pretty different from the illustrated version. But it's also pretty space-efficient. I agree the side-by-side layout might enhance that efficiency even more and opens up the option of 1:many do/don't combinations. 

I put together a series of them, showing both the (A) boxed version and (B) icon version. 

![screen shot 2018-07-30 at 5 08 30 pm](https://user-images.githubusercontent.com/1207666/43423776-48f9be24-941b-11e8-992a-ed585f3181c0.png)

**Comment by jamesmelzer** [comment]
Updated:

![doc components-dodont](https://user-images.githubusercontent.com/1207666/43717192-bfbe8ede-9954-11e8-944e-bbfee18cc162.png)
