### ISSUE TITLE
Layout & Grid - Build

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#177]
Build the layout system explored in prototypes in #176. 

Emphasis here is on building the layout portion, since the formal grid was already established in #119 

See #123 and decide if these two tickets can be consolidated. 

See #127: the page shell should be a separate component, but it's possible it will be convenient to stub it out as part of this ticket.

**Comment by joesnellpdx** [comment]
Waiting for Layout & Grid Prototypes to be approved before continuing:
https://github.com/JDRF/spirit/issues/176

**Comment by joesnellpdx** [comment]
Correction on task requirements (Note to Self):

- Add options for brushes, paint and any other global options not in #176 in addition to requests in initial task.

CC: @jamesmelzer

**Comment by joesnellpdx** [comment]
@jamesmelzer :

- Completed in #176: Build the layout system explored in prototypes in #176

- Completed in #176: Emphasis here is on building the layout portion, since the formal grid was already established in #119 

- Closed #123 as part of the #176 - See #123 and decide if these two tickets can be consolidated. 

- Recommend #127 should be separate component: See #127: the page shell should be a separate component, but it's possible it will be convenient to stub it out as part of this ticket. 

-----

- Current ticket responsibilities: Adding brush top  / bottom and brush background options
- Display new options across breakpoints with different content

**Comment by joesnellpdx** [comment]
@kevinmpowell 

I need to wire up separate sprite compilation process in the build tooling. Will likely need to replicate for other resources down the road (i.e. logos). 

I see the gulp tasks in esds, but not sure how you recommend adding to the Sprit DS. As you have done this before, if I can see how you rig it - it will be able to follow the process next time.

If preferred: You can provide me direction and I can take it from there. 

Will also need to output / upload to the CDN and doc sites.

LMK if you have questions.
