### ISSUE TITLE
Specialized Form Inputs

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#185]
Extend form inputs with these specialized enhancements:

* Date and phone input masks for *input*
* Secure password field, including built-in "show/hide" button and functionality (JS required?)
* Email input, including built-in "sign up" button. 

![screen shot 2018-07-26 at 4 10 25 pm](https://user-images.githubusercontent.com/1207666/43285935-87ac97b6-90ee-11e8-80cb-f4da8733f471.png)

**Comment by kevinmpowell** [comment]
Going with [Vanilla Text Mask](https://github.com/text-mask/text-mask).

There's an open PR to add the functionality to preserve the placeholder as you type per the Spirit Design. https://github.com/text-mask/text-mask/pull/703

I recommend pushing to get that PR merged at the library rather than trying to roll our own functionality. For now, placeholder characters will be replaced with underscores `_` once the user starts typing.

**Comment by kevinmpowell** [comment]
Closing and replacing with #267, #268, #269, #270
